### ISSUE TITLE
Cannot run on Mac M1

### ISSUE THREAD

**Issue by leo-chartier** [algosup/2022-2023-project-5-algorithmics-Team-7#3]
Priority: **Low**

After adapting the basic command from the "usage.txt" file and running it, the program fails to run with the following logs:
`> dotnet WineMixer.dll input/tanks.txt input/recipe.txt`
```
Initializing .... 
Could not find file '/usr/local/share/dotnet/x64/usage.txt'.
Usage: wine-mixer.exe <tanksizes> <winemix> [<optionsfilename>]
Error occurred: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at WineMixer.Mix.LoadFromFile(String fileName) in C:\Users\cdigg\git\wine-mixer\WineMixer\Mix.cs:line 103
   at WineMixer.Configuration.LoadFromFiles(String tankSizeFileName, String wineMixFileName, String optionsFileName) in C:\Users\cdigg\git\wine-mixer\WineMixer\Configuration.cs:line 58
   at WineMixer.Program.Main(String[] args) in C:\Users\cdigg\git\wine-mixer\WineMixer\Program.cs:line 83
```

The inputs are the default ones provided along with the code but have been provided again here:
[inputs/tanks.txt](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/files/11480843/tanks.txt)
[inputs/recipe.txt](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/files/11480844/recipe.txt)

**Comment by cdiggins** [comment]
@leo-chartier : Is this still reproducible with the update on May 30th? It seem that @Quentin-Clement could run the program: https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/issues/7

**Comment by cdiggins** [comment]
I don't understand the issue, does it not run on any Mac? Or is it just one specific Mac?

**Comment by leo-chartier** [comment]
Oh sorry, I updated the report but forgot to close the issue.

The problem occurred on any Mac. I just tried it again and I only get issue #6
